export const GET_APP = 'GET_APP'
// export const GET_BLOG = 'GET_BLOG'
// export const SET_BLOG = 'SET_BLOG'
export const GET_PAGES = 'GET_PAGES'
export const SET_SCROLLED = 'SET_SCROLLED'
export const SET_NAV_STATE = 'SET_NAV_STATE'
export const VIEW_NAV_DRAWER = 'VIEW_NAV_DRAWER'
export const SET_ANIMATION_STATE = 'SET_ANIMATION_STATE'
